/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.config;

import java.util.concurrent.TimeUnit;

import org.apache.cassandra.concurrent.Stage;
import org.apache.cassandra.db.memtable.TrieMemtable;
import org.apache.cassandra.exceptions.ConfigurationException;
import org.apache.cassandra.metrics.TableMetrics;
import org.apache.cassandra.net.MessagingService;
import org.apache.cassandra.schema.DefaultCompressionSelector;
import org.apache.cassandra.sensors.SensorsFactory;
import org.apache.cassandra.service.context.OperationContext;
import org.apache.cassandra.service.reads.range.EndpointGroupingRangeCommandIterator;

/** A class that extracts system properties for the cassandra node it runs within. */
public enum CassandraRelevantProperties
{
    //base JVM properties
    JAVA_HOME("java.home"),
    CASSANDRA_PID_FILE ("cassandra-pidfile"),

    /**
     * Indicates the temporary directory used by the Java Virtual Machine (JVM)
     * to create and store temporary files.
     */
    JAVA_IO_TMPDIR ("java.io.tmpdir"),

    /**
     * Path from which to load native libraries.
     * Default is absolute path to lib directory.
     */
    JAVA_LIBRARY_PATH ("java.library.path"),

    JAVA_SECURITY_EGD ("java.security.egd"),

    /** Java Runtime Environment version */
    JAVA_VERSION ("java.version"),

    /** Java Virtual Machine implementation name */
    JAVA_VM_NAME ("java.vm.name"),

    /** Line separator ("\n" on UNIX). */
    LINE_SEPARATOR ("line.separator"),

    /** Java class path. */
    JAVA_CLASS_PATH ("java.class.path"),

    /** Operating system architecture. */
    OS_ARCH ("os.arch"),

    /** Operating system name. */
    OS_NAME ("os.name"),

    /** User's home directory. */
    USER_HOME ("user.home"),

    /** Platform word size sun.arch.data.model. Examples: "32", "64", "unknown"*/
    SUN_ARCH_DATA_MODEL ("sun.arch.data.model"),

    //JMX properties
    /**
     * The value of this property represents the host name string
     * that should be associated with remote stubs for locally created remote objects,
     * in order to allow clients to invoke methods on the remote object.
     */
    JAVA_RMI_SERVER_HOSTNAME ("java.rmi.server.hostname"),

    /**
     * If this value is true, object identifiers for remote objects exported by this VM will be generated by using
     * a cryptographically secure random number generator. The default value is false.
     */
    JAVA_RMI_SERVER_RANDOM_ID ("java.rmi.server.randomIDs"),

    /**
     * This property indicates whether password authentication for remote monitoring is
     * enabled. By default it is disabled - com.sun.management.jmxremote.authenticate
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_AUTHENTICATE ("com.sun.management.jmxremote.authenticate"),


    /**
     * Controls the JMX server threadpool keap-alive time.
     * Should only be set by in-jvm dtests.
     */
    SUN_RMI_TRANSPORT_TCP_THREADKEEPALIVETIME("sun.rmi.transport.tcp.threadKeepAliveTime"),

    /**
     * Controls the distributed garbage collector lease time for JMX objects.
     * Should only be set by in-jvm dtests.
     */
    JAVA_RMI_DGC_LEASE_VALUE_IN_JVM_DTEST("java.rmi.dgc.leaseValue"),

    /**
     * The port number to which the RMI connector will be bound - com.sun.management.jmxremote.rmi.port.
     * An Integer object that represents the value of the second argument is returned
     * if there is no port specified, if the port does not have the correct numeric format,
     * or if the specified name is empty or null.
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_RMI_PORT ("com.sun.management.jmxremote.rmi.port", "0"),

    /** Cassandra jmx remote port */
    CASSANDRA_JMX_REMOTE_PORT("cassandra.jmx.remote.port"),

    /** Cassandra jmx local port */
    CASSANDRA_JMX_LOCAL_PORT("cassandra.jmx.local.port"),

    /** This property  indicates whether SSL is enabled for monitoring remotely. Default is set to false. */
    COM_SUN_MANAGEMENT_JMXREMOTE_SSL ("com.sun.management.jmxremote.ssl"),

    /**
     * This property indicates whether SSL client authentication is enabled - com.sun.management.jmxremote.ssl.need.client.auth.
     * Default is set to false.
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_SSL_NEED_CLIENT_AUTH ("com.sun.management.jmxremote.ssl.need.client.auth"),

    /**
     * This property indicates the location for the access file. If com.sun.management.jmxremote.authenticate is false,
     * then this property and the password and access files, are ignored. Otherwise, the access file must exist and
     * be in the valid format. If the access file is empty or nonexistent, then no access is allowed.
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_ACCESS_FILE ("com.sun.management.jmxremote.access.file"),

    /** This property indicates the path to the password file - com.sun.management.jmxremote.password.file */
    COM_SUN_MANAGEMENT_JMXREMOTE_PASSWORD_FILE ("com.sun.management.jmxremote.password.file"),

    /** Port number to enable JMX RMI connections - com.sun.management.jmxremote.port */
    COM_SUN_MANAGEMENT_JMXREMOTE_PORT ("com.sun.management.jmxremote.port"),

    /**
     * A comma-delimited list of SSL/TLS protocol versions to enable.
     * Used in conjunction with com.sun.management.jmxremote.ssl - com.sun.management.jmxremote.ssl.enabled.protocols
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_SSL_ENABLED_PROTOCOLS ("com.sun.management.jmxremote.ssl.enabled.protocols"),

    /**
     * A comma-delimited list of SSL/TLS cipher suites to enable.
     * Used in conjunction with com.sun.management.jmxremote.ssl - com.sun.management.jmxremote.ssl.enabled.cipher.suites
     */
    COM_SUN_MANAGEMENT_JMXREMOTE_SSL_ENABLED_CIPHER_SUITES ("com.sun.management.jmxremote.ssl.enabled.cipher.suites"),

    /** mx4jaddress */
    MX4JADDRESS ("mx4jaddress"),

    /** mx4jport */
    MX4JPORT ("mx4jport"),

    RING_DELAY("cassandra.ring_delay_ms", "30000"),

    /**
     * When bootstraping we wait for all schema versions found in gossip to be seen, and if not seen in time we fail
     * the bootstrap; this property will avoid failing and allow bootstrap to continue if set to true.
     */
    BOOTSTRAP_SKIP_SCHEMA_CHECK("cassandra.skip_schema_check"),

    /**
     * When bootstraping how long to wait for schema versions to be seen.
     */
    BOOTSTRAP_SCHEMA_DELAY_MS("cassandra.schema_delay_ms"),

    /**
     * When draining, how long to wait for mutating executors to shutdown.
     */
    DRAIN_EXECUTOR_TIMEOUT_MS("cassandra.drain_executor_timeout_ms", String.valueOf(TimeUnit.MINUTES.toMillis(5))),

    /**
     * Gossip quarantine delay is used while evaluating membership changes and should only be changed with extreme care.
     */
    GOSSIPER_QUARANTINE_DELAY("cassandra.gossip_quarantine_delay_ms"),

    IGNORED_SCHEMA_CHECK_VERSIONS("cassandra.skip_schema_check_for_versions"),

    IGNORED_SCHEMA_CHECK_ENDPOINTS("cassandra.skip_schema_check_for_endpoints"),

    /**
     * Factory to create instances used during log transaction processing
     */
    LOG_TRANSACTIONS_FACTORY("cassandra.log_transactions_factory"),

    /**
     * When doing a host replacement its possible that the gossip state is "empty" meaning that the endpoint is known
     * but the current state isn't known.  If the host replacement is needed to repair this state, this property must
     * be true.
     */
    REPLACEMENT_ALLOW_EMPTY("cassandra.allow_empty_replace_address", "true"),

    /**
     * Whether {@link org.apache.cassandra.db.ConsistencyLevel#NODE_LOCAL} should be allowed.
     */
    ENABLE_NODELOCAL_QUERIES("cassandra.enable_nodelocal_queries", "false"),

    CONSISTENT_DIRECTORY_LISTINGS("cassandra.consistent_directory_listings", "false"),

    /**
     * To provide custom implementation to prioritize compaction tasks in UCS
     */
    UCS_COMPACTION_AGGREGATE_PRIORITIZER("unified_compaction.custom_compaction_aggregate_prioritizer"),

    /**
     * whether to include non-data files size into compaction space estimaton in UCS
     */
    UCS_COMPACTION_INCLUDE_NON_DATA_FILES_SIZE("unified_compaction.include_non_data_files_size", "true"),

    /**
     * Compaction validation mode to determine whether to skip validation or warn on data loss or abort on data loss;
     *
     * Available options: NONE, WARN, ABORT. Default is NONE
     */
    COMPACTION_VALIDATION_MODE("cassandra.compaction_validation_mode", "NONE"),

    /**
     * The factory for handler of the storage of sstables
     */
    REMOTE_STORAGE_HANDLER_FACTORY("cassandra.remote_storage_handler_factory"),

    /**
     * To provide a provider to a different implementation of the truncate statement.
     */
    TRUNCATE_STATEMENT_PROVIDER("cassandra.truncate_statement_provider"),

    /**
     * whether to persist prepared statements in the system table
     */
    PERSIST_PREPARED_STATEMENTS("cassandra.persist_prepared_statements", "true"),

    /**
     * custom native library for os access
     */
    CUSTOM_NATIVE_LIBRARY("cassandra.custom_native_library"),

    /**
     * Repair progress reporter, default using system distributed keyspace
     */
    REPAIR_PROGRESS_REPORTER("cassandra.custom_repair_progress_reporter_class"),

    /**
     * Listen to repair parent session lifecycle
     */
    REPAIR_PARENT_SESSION_LISTENER("cassandra.custom_parent_repair_session_listener_class"),

    /**
     * Allow repair in mixed major version clusters. When false (default), repair operations
     * will fail in clusters with mixed major versions unless explicitly allowed.
     * Set to true to allow repair during rolling upgrades.
     */
    ALLOW_MIXED_REPAIR("cassandra.allow_mixed_repair", "false"),

    //cassandra properties (without the "cassandra." prefix)

    /**
     * The cassandra-foreground option will tell CassandraDaemon whether
     * to close stdout/stderr, but it's up to us not to background.
     * yes/null
     */
    CASSANDRA_FOREGROUND ("cassandra-foreground"),

    DEFAULT_PROVIDE_OVERLAPPING_TOMBSTONES ("default.provide.overlapping.tombstones"),
    ORG_APACHE_CASSANDRA_DISABLE_MBEAN_REGISTRATION ("org.apache.cassandra.disable_mbean_registration"),

    /**
     * Disables user-defined functions (UDFs). When set to true, UDF creation and execution are blocked.
     * This property can be used to forcibly disable UDFs for security reasons, or when running on JDK
     * versions where SecurityManager-based sandboxing may not be reliable or available.
     */
    DISABLE_USER_DEFINED_FUNCTIONS("cassandra.disable_user_defined_functions", "false"),

    //only for testing
    ORG_APACHE_CASSANDRA_CONF_CASSANDRA_RELEVANT_PROPERTIES_TEST("org.apache.cassandra.conf.CassandraRelevantPropertiesTest"),
    ORG_APACHE_CASSANDRA_DB_VIRTUAL_SYSTEM_PROPERTIES_TABLE_TEST("org.apache.cassandra.db.virtual.SystemPropertiesTableTest"),

    /** This property indicates whether disable_mbean_registration is true */
    IS_DISABLED_MBEAN_REGISTRATION("org.apache.cassandra.disable_mbean_registration"),

    /** what class to use for mbean registeration */
    MBEAN_REGISTRATION_CLASS("org.apache.cassandra.mbean_registration_class"),

    MEMTABLE_TRIE_SIZE_LIMIT("cassandra.trie_size_limit_mb"),

    /**
     * Maximum number of log statements cached per NoSpamLogger instance.
     * This prevents unbounded memory growth when log messages contain dynamic content.
     * Defaults to MAX_VALUE as a default behavior since we rely on the cache time-based expiration.
     */
    NOSPAM_LOGGER_MAX_STATEMENTS_PER_LOGGER("cassandra.nospam_logger.max_statements_per_logger", String.valueOf(Long.MAX_VALUE)),

    /** This property indicates if the code is running under the in-jvm dtest framework */
    DTEST_IS_IN_JVM_DTEST("org.apache.cassandra.dtest.is_in_jvm_dtest"),

    /** Represents the maximum size (in bytes) of a serialized mutation that can be cached **/
    CACHEABLE_MUTATION_SIZE_LIMIT("cassandra.cacheable_mutation_size_limit_bytes", Long.toString(1_000_000)),

    MIGRATION_DELAY("cassandra.migration_delay_ms", "60000"),
    /** Defines how often schema definitions are pulled from the other nodes */
    SCHEMA_PULL_INTERVAL_MS("cassandra.schema_pull_interval_ms", "60000"),
    /**
     * Minimum delay after a failed pull request before it is reattempted. It prevents reattempting failed requests
     * immediately as it is high chance they will fail anyway. It is better to wait a bit instead of flooding logs
     * and wasting resources.
     */
    SCHEMA_PULL_BACKOFF_DELAY_MS("cassandra.schema_pull_backoff_delay_ms", "3000"),

    /** When enabled, recursive directory deletion will be executed using a unix command `rm -rf` instead of traversing
     * and removing individual files. This is now used only tests, but eventually we will make it true by default.*/
    USE_NIX_RECURSIVE_DELETE("cassandra.use_nix_recursive_delete"),

    /** If set, {@link org.apache.cassandra.net.MessagingService} is shutdown abrtuptly without waiting for anything.
     * This is an optimization used in unit tests becuase we never restart a node there. The only node is stopoped
     * when the JVM terminates. Therefore, we can use such optimization and not wait unnecessarily. */
    NON_GRACEFUL_SHUTDOWN("cassandra.test.messagingService.nonGracefulShutdown"),

    /** Disables flush changes to local and schema keyspaces. Also, disables recycling all segments of commitlog after
     * dropping a table. Tests which do not restart nodes may enable this option in order to run faster. Note that this
     * is enabled for unit tests but if an individual test requires schema to be flushed, it can be also done manually
     * for that particular case: {@code flush(SchemaConstants.SCHEMA_KEYSPACE_NAME);}. */
    UNSAFE_SYSTEM("cassandra.unsafesystem", "false"),

    /**
     * Delay before checking if gossip is settled.
     */
    GOSSIP_SETTLE_MIN_WAIT_MS("cassandra.gossip_settle_min_wait_ms", "5000"),

    /**
     * Interval delay between checking gossip is settled.
     */
    GOSSIP_SETTLE_POLL_INTERVAL_MS("cassandra.gossip_settle_interval_ms", "1000"),

    /**
     * Number of polls without gossip state change to consider gossip as settled.
     */
    GOSSIP_SETTLE_POLL_SUCCESSES_REQUIRED("cassandra.gossip_settle_poll_success_required", "3"),

    /** Which class to use for token metadata provider */
    CUSTOM_TMD_PROVIDER_PROPERTY("cassandra.custom_token_metadata_provider_class"),

    /** Which class to use for failure detection */
    CUSTOM_FAILURE_DETECTOR_PROPERTY("cassandra.custom_failure_detector_class"),

    /** Set this property to true in order to switch to micrometer metrics */
    USE_MICROMETER("cassandra.use_micrometer_metrics", "false"),

    /** Set this property to true in order to use DSE-like histogram bucket boundaries and behaviour */
    USE_DSE_COMPATIBLE_HISTOGRAM_BOUNDARIES("cassandra.use_dse_compatible_histogram_boundaries", "false"),

    /** Which class to use for coordinator client request metrics */
    CUSTOM_CLIENT_REQUEST_METRICS_PROVIDER_PROPERTY("cassandra.custom_client_request_metrics_provider_class"),

    /**
     * Which class to use for internode metrics for {@link org.apache.cassandra.net.OutboundConnections}.
     * The provided class name must point to an implementation of {@link org.apache.cassandra.metrics.InternodeOutboundMetrics}.
     */
    CUSTOM_INTERNODE_INBOUND_METRICS_PROVIDER_PROPERTY("cassandra.custom_internode_inbound_metrics_provider_class"),

    /**
     * Which class to use for messaging metrics for {@link org.apache.cassandra.net.MessagingService}.
     * The provided class name must point to an implementation of {@link org.apache.cassandra.metrics.MessagingMetrics}.
     */
    CUSTOM_MESSAGING_METRICS_PROVIDER_PROPERTY("cassandra.custom_messaging_metrics_provider_class"),

    /**
     * Which class to use for internode metrics for {@link org.apache.cassandra.net.OutboundConnections}.
     * The provided class name must point to an implementation of {@link org.apache.cassandra.metrics.InternodeOutboundMetrics}.
     */
    CUSTOM_INTERNODE_OUTBOUND_METRICS_PROVIDER_PROPERTY("cassandra.custom_internode_outbound_metrics_provider_class"),

    /**
     * Which class to use for creating guardrails
     */
    CUSTOM_GUARDRAILS_FACTORY_PROPERTY("cassandra.custom_guardrails_factory_class"),

    /**
     * Which class to use when notifying about stage task execution
     */
    CUSTOM_TASK_EXECUTION_CALLBACK_CLASS("cassandra.custom_task_execution_callback_class"),

    /**
     * Used to support directory creation for different file system and remote/local conversion
     */
    CUSTOM_STORAGE_PROVIDER("cassandra.custom_storage_provider"),

    /** Watcher used when opening sstables to discover extra components, eg. archive component */
    CUSTOM_SSTABLE_WATCHER("cassandra.custom_sstable_watcher"),

    /** Defines the interval for reporting any operations that have timed out.  */
    MONITORING_REPORT_INTERVAL_MS("cassandra.monitoring_report_interval_ms", "5000"),

    /**
     * Defines the maximum number of unique timed out queries that will be reported in the logs.
     * Use a negative number to remove any limit.
     */
    MONITORING_MAX_OPERATIONS("cassandra.monitoring_max_operations", "50"),

    /**
     * Whether to log detailed execution info when logging slow non-SAI queries.
     * For SAI queries, see {@link #SAI_MONITORING_EXECUTION_INFO_ENABLED}.
     */
    MONITORING_EXECUTION_INFO_ENABLED("cassandra.monitoring_execution_info_enabled", "true"),

    /**
     * Whether to skip secondary indexes when the query specifies full primary keys.
     * In principle, there is no reason to prefer using the indexes in such queries,
     * and this exists just as a feature gate.
     */
    SKIP_INDEXES_ON_FULL_PRIMARY_KEYS("cassandra.index.skip_on_full_primary_keys", "true"),

    /** The current version of the SAI on-disk index format. */
    SAI_CURRENT_VERSION("cassandra.sai.latest.version", "ec"),

    /** The class to use for selecting the current version of the SAI on-disk index format on a per-keyspace basis. */
    SAI_VERSION_SELECTOR_CLASS("cassandra.sai.version.selector.class", ""),

    /** Controls the maximum top-k limit for vector search */
    SAI_VECTOR_SEARCH_MAX_TOP_K("cassandra.sai.vector_search.max_top_k", "1000"),

    /** Controls the hnsw vector cache size, in bytes, per index segment. 0 to disable */
    SAI_HNSW_VECTOR_CACHE_BYTES("cassandra.sai.vector_search.vector_cache_bytes", String.valueOf(4 * 1024 * 1024)),

    /** Whether to validate terms that will be SAI indexed at the coordinator */
    SAI_VALIDATE_TERMS_AT_COORDINATOR("cassandra.sai.validate_terms_at_coordinator", "true"),

    /** Whether to optimize query plans */
    SAI_QUERY_OPTIMIZATION_LEVEL("cassandra.sai.query_optimization_level", "1"),

    /**
     * If disabled, the query optimizer runs index search to estimate the number of matching keys.
     * If enabled, the query optimizer uses, if present, the term statistics stored
     * with the help of histograms in the metadata component of each SSTable index.
     * Using terms statistics is significantly less costly but less precise.
     */
    SAI_QUERY_OPTIMIZATION_USE_TERM_STATISTICS("cassandra.sai.query_optimization.use_term_statistics", "false"),

    /** Controls the number of rows read in a single batch when fetching rows for a partition key */
    SAI_PARTITION_ROW_BATCH_SIZE("cassandra.sai.partition_row_batch_size", "100"),

    /** Controls the maximum number of expressions that will be used in a SAI intersection operation. */
    SAI_INTERSECTION_CLAUSE_LIMIT("cassandra.sai.intersection.clause.limit", "2"),

    /**
     * Whether to log SAI-specific detailed execution info when logging slow SAI queries.
     * This execution info includes the query metrics and the query plan of the slow queries.
     * For non-SAI queries, see {@link #MONITORING_EXECUTION_INFO_ENABLED}.
     */
    SAI_MONITORING_EXECUTION_INFO_ENABLED("cassandra.sai.monitoring_execution_info_enabled", "true"),

    /** Whether vector type only allows float vectors. True by default. **/
    VECTOR_FLOAT_ONLY("cassandra.float_only_vectors", "true"),
    /** Enables use of vector type. True by default. **/
    VECTOR_TYPE_ALLOWED("cassandra.vector_type_allowed", "true"),
    // Use non-positive value to disable it. Period in millis to trigger a flush for memtable
    FLUSH_PERIOD_IN_MILLIS("cassandra.flush_period_in_millis", "-1"),
    // Use non-positive value to disable it. When num of rows in SAI non-vector memtable index reaches the threshold, it triggers flush
    SAI_NON_VECTOR_FLUSH_THRESHOLD_MAX_ROWS("cassandra.sai.non_vector_flush_threshold_max_rows", "-1"),
    // Use non-positive value to disable it. Period in millis to trigger a flush for SAI non-vector memtable index.
    SAI_NON_VECTOR_FLUSH_PERIOD_IN_MILLIS("cassandra.sai.non_vector_flush_period_in_millis", "-1"),
    // Use non-positive value to disable it. When num of rows in SAI vector memtable index reaches the threshold, it triggers flush
    SAI_VECTOR_FLUSH_THRESHOLD_MAX_ROWS("cassandra.sai.vector_flush_threshold_max_rows", "-1"),
    // Use non-positive value to disable it. Period in millis to trigger a flush for SAI vector memtable index.
    SAI_VECTOR_FLUSH_PERIOD_IN_MILLIS("cassandra.sai.vector_flush_period_in_millis", "-1"),
    /**
     * Whether compaction should build vector indexes using a fused graph, i.e. a graph where the quantized vectors
     * are stored inline with the graph nodes (FusedPQ). This is an experimental feature that significantly increases
     * disk usage and should only be enabled where it makes sense.
     * See: <a href="https://github.com/riptano/cndb/issues/17471">CNDB-17471</a>
     * <p>
     * Note: for indexes using version FA (jvector file format version 6), FusedPQ is always enabled regardless
     * of this property. For version FB and later, this property controls whether FusedPQ is used.
     */
    SAI_VECTOR_ENABLE_FUSED("cassandra.sai.vector.enable_fused", "false"),
    // Use nvq when building graphs in compaction. Disabled by default for now. Enabling will reduce recall slightly
    // while also reducing the storage footprint.
    SAI_VECTOR_ENABLE_NVQ("cassandra.sai.vector.enable_nvq", "false"),
    // NVQ number of subvectors. This isn't really expected to change much so we're only exposing
    // it as a global variable in case it's needed.
    SAI_VECTOR_NVQ_NUM_SUB_VECTORS("cassandra.sai.vector.nvq_num_sub_vectors", "2"),
    // The allowed ratio of extra rows (that map to "holes" in the ordinal space) to total rows indexed in the graph
    // Higher percentages will result in more memory utilized to store the extra postings mappings and larger graph
    // file sizes to store the empty nodes.
    SAI_VECTOR_ORDINAL_HOLE_DENSITY_LIMIT("cassandra.sai.vector.ordinal_hole_density_limit", "0.01"),
    // When building a compaction graph, encode layer 0 nodes in parallel and subsequently use async io for writes.
    // This feature is experimental, so defaults to false.
    SAI_ENCODE_AND_WRITE_VECTOR_GRAPH_IN_PARALLEL_ENABLED("cassandra.sai.vector.encode_and_write_graph_in_parallel.enabled", "false"),
    // When parallel graph encoding is enabled, the number of threads to use for encoding. Defaults to 0, meaning
    // use all available processors as reported by the JVM.
    SAI_ENCODE_AND_WRITE_VECTOR_GRAPH_IN_PARALLEL_NUM_THREADS("cassandra.sai.vector.encode_and_write_graph_in_parallel.num_threads", "0"),
    // When parallel graph encoding is enabled, whether to use director buffers. Defaults to false, meaning heap
    // buffers are used. A buffer will be allocated per encoding thread. The size of each buffer is the size
    // of the encoded graph node at layer 0, which varies based on graph feature settings.
    SAI_ENCODE_AND_WRITE_VECTOR_GRAPH_IN_PARALLEL_USE_DIRECT_BUFFERS("cassandra.sai.vector.encode_and_write_graph_in_parallel.use_direct_buffers", "false"),

    /**
     * Whether to disable auto-compaction
     */
    DISABLED_AUTO_COMPACTION_PROPERTY("cassandra.disabled_auto_compaction"),

    /** Which class to use for dynamic snitch severity values */
    DYNAMIC_SNITCH_SEVERITY_PROVIDER("cassandra.dynamic_snitch_severity_provider"),

    NEVER_PURGE_TOMBSTONES_PROPERTY("cassandra.never_purge_tombstones"),

    SYSTEM_DISTRIBUTED_NTS_RF_OVERRIDE_PROPERTY("cassandra.system_distributed_replication_per_dc"),
    SYSTEM_DISTRIBUTED_NTS_DC_OVERRIDE_PROPERTY("cassandra.system_distributed_replication_dc_names"),

    // in OSS, when UUID based SSTable generation identifiers are enabled, they use TimeUUID
    // though, for CNDB we want to use ULID - this property allows for that
    // valid values for this property are: uuid, ulid
    SSTABLE_UUID_IMPL("cassandra.sstable.id.uuid_impl", "uuid"),

    /**
     * Name of a custom implementation of {@link org.apache.cassandra.service.Mutator}.
     */
    CUSTOM_MUTATOR_CLASS("cassandra.custom_mutator_class"),

    /** Whether to skip rewriting hints when original host id left the cluster */
    SKIP_REWRITING_HINTS_ON_HOST_LEFT("cassandra.hinted_handoff.skip_rewriting_hints_on_host_left"),

    CUSTOM_HINTS_HANDLER("cassandra.custom_hints_handler"),
    CUSTOM_HINTS_ENDPOINT_PROVIDER("cassandra.custom_hints_endpoint_provider"),

    USE_RANDOM_ALLOCATION_IF_NOT_SUPPORTED("cassandra.token_allocation.use_random_if_not_supported"),

    COMPACTION_HISTORY_ENABLED("cassandra.compaction_history_enabled", "true"),

    // Allows one to turn off cursors in compaction.
    CURSORS_ENABLED("cassandra.allow_cursor_compaction", "true"),

    SYNC_LAG_FACTOR("cassandra.commitlog_sync_block_lag_factor", "1.5"),

    CDC_STREAMING_ENABLED("cassandra.cdc.enable_streaming", "true"),
    // Default metric aggegration strategy for tables without aggregation explicitly set.
    TABLE_METRICS_DEFAULT_HISTOGRAMS_AGGREGATION("cassandra.table_metrics_default_histograms_aggregation", TableMetrics.MetricsAggregation.INDIVIDUAL.name()),
    // Determines if table metrics should be also exported to shared global metric
    TABLE_METRICS_EXPORT_GLOBALS("cassandra.table_metrics_export_globals", "true"),
    // Enable/disable replica response size metrics collection
    REPLICA_RESPONSE_SIZE_METRICS_ENABLED("cassandra.replica_response_size_metrics_enabled", "true"),
    FILE_CACHE_SIZE_IN_MB("cassandra.file_cache_size_in_mb", "2048"),
    CUSTOM_HINTS_RATE_LIMITER_FACTORY("cassandra.custom_hints_rate_limiter_factory"),

    CUSTOM_INDEX_BUILD_DECIDER("cassandra.custom_index_build_decider"),

    // Allows admin to include only some system views (see two below)
    SYSTEM_VIEWS_INCLUDE_ALL("cassandra.system_view.include_all", "true"),
    //This only applies if include all is false
    SYSTEM_VIEWS_INCLUDE_LOCAL_AND_PEERS("cassandra.system_view.include_local_and_peers"),
    //This only applies if include all is false
    SYSTEM_VIEWS_INCLUDE_INDEXES("cassandra.system_view.include_indexes"),

    // Allow disabling deletions of corrupt index components for troubleshooting
    DELETE_CORRUPT_SAI_COMPONENTS("cassandra.sai.delete_corrupt_components", "true"),
    // Allows to force the creation of new component files when rebuilding SAI indexes. By default (when this is `false`),
    // when a SAI index is rebuilt, the newly created component files overwrite the old ones, which implies a rebuild
    // cannot be done without first stopping reads on that index. Enabling this option will instead keep the old
    // files untouched, and create new files (with a different file name) instead.
    IMMUTABLE_SAI_COMPONENTS("cassandra.sai.immutable_components", "false"),
    // Minimum SAI index version to which immutable components can apply. If the SAI version used is strictly lower
    // that the version configured here, then immutable components will _not_ be used even if the previous flag is set
    // to `true`. You can set this to `aa` to enable immutable components on every version.
    IMMUTABLE_SAI_COMPONENTS_MIN_VERSION("cassandra.sai.immutable_components.min_version", "ca"),

    // The quantile used by the dynamic endpoint snitch to compute the score for a replica.
    DYNAMIC_ENDPOINT_SNITCH_QUANTILE("cassandra.dynamic_endpoint_snitch_quantile", "0.5"),

    // whether to quantize the dynamic endpoint snitch score to milliseconds; if set to false the nanosecond measurement
    // is used
    DYNAMIC_ENDPOINT_SNITCH_QUANTIZE_TO_MILLIS("cassandra.dynamic_endpoint_snitch_quantize_to_millis", "true"),
    // bloom filter lazy loading
    /**
     * true if non-local table's bloom filter should be deserialized on read instead of when opening sstable
     */
    BLOOM_FILTER_LAZY_LOADING("cassandra.bloom_filter_lazy_loading", "false"),

    /**
     * sstable primary index hits per second to determine if a sstable is hot. 0 means BF should be loaded immediately on read.
     *
     * Note that when WINDOW <= 0, this is used as absolute primary index access count.
     */
    BLOOM_FILTER_LAZY_LOADING_THRESHOLD("cassandra.bloom_filter_lazy_loading.threshold", "0"),

    /**
     * Window of time by minute, available: 1 (default), 5, 15, 120.
     *
     * Note that if <= 0 then we use threshold as the absolute count
     */
    BLOOM_FILTER_LAZY_LOADING_WINDOW("cassandra.bloom_filter_lazy_loading.window", "1"),

    // Allows skipping advising the OS to free cached pages associated commitlog flushing
    COMMITLOG_SKIP_FILE_ADVICE("cassandra.commitlog.skip_file_advice"),

    // Changes the semantic of the "THREE" consistency level to mean "all but one"
    // i.e. that all replicas except for at most one in the cluster (across all DCs) must accept the write for it to be successful.
    THREE_MEANS_ALL_BUT_ONE("dse.consistency_level.three_means_all_but_one", "false"),
    /**
     * Allows to set a custom response messages handler for verbs {@link org.apache.cassandra.net.Verb#REQUEST_RSP} and
     * {@link org.apache.cassandra.net.Verb#FAILURE_RSP}.
     */
    CUSTOM_RESPONSE_VERB_HANDLER_PROVIDER("cassandra.custom_response_verb_handler_provider_class"),
    VALIDATE_MAX_TERM_SIZE_AT_COORDINATOR("cassandra.sai.validate_max_term_size_at_coordinator"),
    CUSTOM_KEYSPACES_FILTER_PROVIDER("cassandra.custom_keyspaces_filter_provider_class"),

    LWT_LOCKS_PER_THREAD("cassandra.lwt_locks_per_thread", "1024"),
    LWT_MIN_BACKOFF_MS("cassandra.lwt_min_backoff_ms", "5"),
    LWT_MAX_BACKOFF_MS("cassandra.lwt_max_backoff_ms", "50"),
    COUNTER_LOCK_NUM_STRIPES_PER_THREAD("cassandra.counter_lock.num_stripes_per_thread", "1024"),
    COUNTER_LOCK_FAIR_LOCK("cassandra.counter_lock.fair_lock", "false"),
    USE_DYNAMIC_SNITCH_FOR_COUNTER_LEADER("cassandra.counter_leader.use_dynamic_snitch", "false"),

    CUSTOM_READ_OBSERVER_FACTORY("cassandra.custom_read_observer_factory_class"),
    /**
     * Whether to enable the use of {@link EndpointGroupingRangeCommandIterator}
     */
    RANGE_READ_ENDPOINT_GROUPING_ENABLED("cassandra.range_read_endpoint_grouping_enabled", "true"),
    /**
     * Allows to set custom current trie index format. This node will produce sstables in this format.
     */
    TRIE_INDEX_FORMAT_VERSION("cassandra.trie_index_format_version", "cc"),

    /**
     * Number of replicas required to store batchlog for atomicity, only accepts values of 1 or 2.
     */
    REQUIRED_BATCHLOG_REPLICA_COUNT("cassandra.batchlog.required_replica_count", "2"),

    /**
     * This property should be enabled when upgrading from the version of Cassandra that allowed to create maps with
     * duration type as a key if the schema contains such columns. It was a bug that the validation didn't prevent
     * from creating such maps but once they are created, we need to be able to read them - hence this property.
     * When the check is enabled, Cassandra falls back to the old behavior and let the user load the data with such
     * maps. When the check is disabled, Cassandra will refuse to load the data with such maps and won't start if
     * the schema contains them.
     */
    DURATION_IN_MAPS_COMPATIBILITY_MODE("cassandra.types.map.duration_in_map_compatibility_mode", "false"),

    /**
     * If this is true, compaction will not verify that sstables selected for compaction are in the same repair
     * state. This check is done to ensure that incremental repair is not improperly carried out (potentially causing
     * data loss) if a node has somehow entered an invalid state. The flag should only be used to recover from
     * situations where sstables are brought in from outside and carry over stale and unapplicable repair state.
     */
    COMPACTION_SKIP_REPAIR_STATE_CHECKING("cassandra.compaction.skip_repair_state_checking", "false"),

    /**
     * If this is true, compaction will not verify that sstables selected for compaction are marked compacted.
     */
    COMPACTION_SKIP_COMPACTING_STATE_CHECKING("cassandra.compaction.skip_compacting_state_checking", "false"),

    /** The length of time to wait for task cessation when we want to run something with compactions disabled. */
    CESSATION_WAIT_SECONDS("cassandra.task_cessation_wait_seconds"),

    /**
     * If true, the searcher object created when opening a SAI index will be replaced by a dummy object and index
     * are never marked queriable (querying one will fail). This is obviously usually undesirable, but can be used if
     * the node only compact sstables to avoid loading heavy index data structures in memory that are not used.
     */
    SAI_INDEX_READS_DISABLED("cassandra.sai.disabled_reads", "false"),

    /**
     * Allows custom implementation of {@link SensorsFactory} to optionally create
     * and configure {@link org.apache.cassandra.sensors.RequestSensors} instances.
     */
    SENSORS_FACTORY("cassandra.sensors_factory_class"),

    /**
     * This property allows configuring the maximum time that CachingRebufferer.rebuffer will wait when waiting for a
     * CompletableFuture fetched from the cache to complete. This is part of a migitation for DBPE-13261.
     */
    CHUNK_CACHE_REBUFFER_WAIT_TIMEOUT_MS("cassandra.chunk_cache_rebuffer_wait_timeout_ms", "30000"),

    /** Class used to discover/load the proper SAI index components file for a given sstable. */
    CUSTOM_SAI_INDEX_COMPONENTS_DISCOVERY("cassandra.sai.custom_components_discovery_class"),

    /**
     * Whether to enable SAI per-table metrics for different kinds of query, such as filter-only queries, top-k-only
     * queries, hybrid queries, single-partition queries, and multipartition queries. These metrics are always counters.
     */
    SAI_QUERY_KIND_PER_TABLE_METRICS_ENABLED("cassandra.sai.metrics.query_kind.per_table.enabled", "true"),

    /**
     * Whether to enable SAI per-query metrics for different kinds of query, such as filter-only queries, top-k-only
     * queries, hybrid queries, single-partition queries, and multipartition queries. These metrics are histograms and
     * timers.
     */
    SAI_QUERY_KIND_PER_QUERY_METRICS_ENABLED("cassandra.sai.metrics.query_kind.per_query.enabled", "false"),

    /**
     * Whether to enable SAI query plan metrics such as the estimated cost, estimated number of rows,
     * number of indexes used in the original and optimized query plan, etc.
     * These metrics are counters and histograms.
     */
    SAI_QUERY_PLAN_METRICS_ENABLED("cassandra.sai.metrics.query_plan.enabled", "true"),

    /**
     * Whether to enable SAI index metrics such as memtable flush metrics, compaction metrics, and disk usage metrics.
     * These metrics include timers, histograms, counters, and gauges for index operations.
     */
    SAI_INDEX_METRICS_ENABLED("cassandra.sai.metrics.index.enabled", "true"),

    /**
     * Whether to enable SAI table state metrics such as disk usage, queryable index count, and index build progress.
     * These metrics include gauges for table-level SAI state information.
     */
    SAI_TABLE_STATE_METRICS_ENABLED("cassandra.sai.metrics.table_state.enabled", "true"),

    /**
     * Whether to enable SAI histogram metrics added after May 2025 release, including
     * {@link org.apache.cassandra.index.sai.metrics.IndexMetrics#memtableIndexWriteLatency},
     * {@link org.apache.cassandra.index.sai.metrics.ColumnQueryMetrics.TrieIndexMetrics#termsTraversalTotalTime},
     * {@link org.apache.cassandra.index.sai.metrics.ColumnQueryMetrics.BKDIndexMetrics#intersectionLatency}, and
     * {@link org.apache.cassandra.index.sai.metrics.TableQueryMetrics.PerQuery#queryLatency}.
     * Enabled by default.
     */
    SAI_HISTOGRAMS_ENABLED("cassandra.sai.metrics.histograms.enabled", "true"),

    /**
     * If true, while creating or altering schema, NetworkTopologyStrategy won't check if the DC exists.
     * This is to remain compatible with older workflows that first change the replication before adding the nodes.
     * Otherwise, it will validate that the names match existing DCs before allowing replication change.
     */
    DATACENTER_SKIP_NAME_VALIDATION("cassandra.dc_skip_name_validation", "false"),
    /**
     * If provided, this custom factory class will be used to create stage executor for a couple of stages.
     * @see Stage for details
     */
    CUSTOM_STAGE_EXECUTOR_FACTORY_PROPERTY("cassandra.custom_stage_executor_factory_class"),

    /**
     * If true, makes read and write CQL statements async, splitting them from the {@link org.apache.cassandra.concurrent.Stage#NATIVE_TRANSPORT_REQUESTS}
     * stage and into the {@link org.apache.cassandra.concurrent.Stage#COORDINATE_READ} and {@link org.apache.cassandra.concurrent.Stage#COORDINATE_MUTATION}
     * stages respectively; in other words, the native transport stage will not block, offloading request processing
     * (and any related blocking behaviour) to the specific read and write stages.
     */
    NATIVE_TRANSPORT_ASYNC_READ_WRITE_ENABLED("cassandra.transport.async.read_write", "false"),

    /**
     * Minimum time that needs to pass after the cluster is detected as fully upgraded to report that there is
     * no upgrade in progress (when using the default cluster version provider).
     */
    CLUSTER_VERSION_PROVIDER_MIN_STABLE_DURATION("cassandra.cluster_version_provider.min_stable_duration_ms", "60000"),

    /**
     * The class name of the custom cluster version provider to use.
     */
    CLUSTER_VERSION_PROVIDER_CLASS_NAME("cassandra.cluster_version_provider.class_name"),

    /**
     * Do not wait for gossip to be enabled before starting stabilisation period. This is required especially for tests
     * which do not enable gossip at all.
     */
    CLUSTER_VERSION_PROVIDER_SKIP_WAIT_FOR_GOSSIP("cassandra.test.cluster_version_provider.skip_wait_for_gossip"),

    /**
     * If true, the coordinator will propagate sensors via the native protocol custom payload bytes map.
     */
    SENSORS_VIA_NATIVE_PROTOCOL("cassandra.sensors_via_native_protocol", "false"),

    /**
     * The current messaging version. This is used when we add new messaging versions without adopting them immediately,
     * or to force the node to use a specific version for testing purposes.
     */
    @Deprecated // remove when cndb no longer supports bdp/6.8-cndb
    DS_CURRENT_MESSAGING_VERSION("ds.current_messaging_version", Integer.toString(MessagingService.VERSION_DS_11)),

    /**
     * Fully-qualified class name of a {@link org.apache.cassandra.schema.CompressionParams.Selector} implementation
     * to use for selecting the default SSTable compression per keyspace.
     * If not set, {@link org.apache.cassandra.schema.DefaultCompressionSelector} is used.
     * <p>
     * This property is read once at startup and cannot be changed dynamically, but the selector implementation
     * can select the compressor dynamically.
     */
    SSTABLE_COMPRESSION_SELECTOR_CLASS("cassandra.sstable.compression.selector.class", DefaultCompressionSelector.class.getName()),

    /**
     * Do not try to calculate optimal streaming candidates. This can take a lot of time in some configs specially
     * with vnodes.
     */
    SKIP_OPTIMAL_STREAMING_CANDIDATES_CALCULATION("cassandra.skip_optimal_streaming_candidates_calculation", "false"),

    /**
     * For reads that use prefetching (sequential ones), how much data is prefetced in kilobytes. If the value set is <= 0, then
     * prefetching is disabled. Also see {@link #READ_PREFETCHING_WINDOW}.
     * <p>
     * This is disabled by default because read prefectching is already provided by the OS when working with local disks.
     * But this is meant for tiered storage extensions, where prefetching may not be provided by the underlying
     * (custom) "filesystem".
     */
    READ_PREFETCHING_SIZE_KB("cassandra.read_prefetching_size_kb", "-1"),

    /**
     * The window (on the prefetching size) used to triggered prefetching. The prefetching algorithm ensures that at least
     * {@link #READ_PREFETCHING_WINDOW} * {@link #READ_PREFETCHING_SIZE_KB} prefetching has been requested, and if that's
     * not the case it requests up to {@link #READ_PREFETCHING_SIZE_KB}.
     */
    READ_PREFETCHING_WINDOW("cassandra.read_prefetching_window", "0.5"),

    /**
     * Number of threads used for read prefetching (when enabled). If unsed, a default based on the number of processors
     * is used.
     */
    READ_PREFETCHING_THREADS("cassandra.read_prefetching_threads"),

    /**
     * Allows custom implementation of {@link OperationContext.Factory} to optionally create and configure custom
     * {@link OperationContext} instances.
     */
    OPERATION_CONTEXT_FACTORY("cassandra.operation_context_factory_class"),

    /**
     * Number of shards for TrieMemtable. If not specified, defaults to {@link TrieMemtable#autoShardCount}
     */
    TRIE_MEMTABLE_SHARD_COUNT("cassandra.trie.memtable.shard.count"),

    /**
     * Whether to use fair locking for TrieMemtable shard locks. Defaults to false.
     */
    TRIE_MEMTABLE_SHARD_LOCK_FAIRNESS("cassandra.trie.memtable.shard.lock.fairness", "false"),

    /**
     * A directory to the default system key location - used by transparent data encryption
     */
    SYSTEM_KEY_DIRECTORY("cassandra.system_key_directory", "/etc/cassandra/conf"),

    TEST_INTERVAL_TREE_EXPENSIVE_CHECKS("cassandra.test.interval_tree_expensive_checks");

    CassandraRelevantProperties(String key, String defaultVal)
    {
        this.key = key;
        this.defaultVal = defaultVal;
    }

    CassandraRelevantProperties(String key)
    {
        this.key = key;
        this.defaultVal = null;
    }

    private final String key;
    private final String defaultVal;

    public String getKey()
    {
        return key;
    }

    /**
     * Gets the value of the indicated system property.
     * @return system property value if it exists, defaultValue otherwise.
     */
    public String getString()
    {
        String value = System.getProperty(key);

        return value == null ? defaultVal : STRING_CONVERTER.convert(value);
    }

    /**
     * Sets the property to its default value if a default value was specified. Remove the property otherwise.
     */
    public void reset()
    {
        if (defaultVal != null)
            System.setProperty(key, defaultVal);
        else
            System.getProperties().remove(key);
    }

    /**
     * Gets the value of a system property as a String.
     * @return system property String value if it exists, overrideDefaultValue otherwise.
     */
    public String getString(String overrideDefaultValue)
    {
        String value = System.getProperty(key);
        if (value == null)
            return overrideDefaultValue;

        return STRING_CONVERTER.convert(value);
    }

    /**
     * Sets the value into system properties.
     * @param value to set
     */
    public void setString(String value)
    {
        System.setProperty(key, value);
    }

    /**
     * Gets the value of a system property as a boolean.
     * @return system property boolean value if it exists, false otherwise().
     */
    public boolean getBoolean()
    {
        String value = System.getProperty(key);

        return BOOLEAN_CONVERTER.convert(value == null ? defaultVal : value);
    }

    /**
     * Gets the value of a system property as a boolean.
     * @return system property boolean value if it exists, overrideDefaultValue otherwise.
     */
    public boolean getBoolean(boolean overrideDefaultValue)
    {
        String value = System.getProperty(key);
        if (value == null)
            return overrideDefaultValue;

        return BOOLEAN_CONVERTER.convert(value);
    }

    /**
     * Sets the value into system properties.
     * @param value to set
     */
    public void setBoolean(boolean value)
    {
        System.setProperty(key, Boolean.toString(value));
    }

    /**
     * Gets the value of a system property as a int.
     * @return system property int value if it exists, defaultValue otherwise.
     */
    public int getInt()
    {
        String value = System.getProperty(key);

        return INTEGER_CONVERTER.convert(value == null ? defaultVal : value);
    }

    /**
     * Gets the value of a system property as a int.
     * @return system property int value if it exists, overrideDefaultValue otherwise.
     */
    public int getInt(int overrideDefaultValue)
    {
        String value = System.getProperty(key);
        if (value == null)
            return overrideDefaultValue;

        return INTEGER_CONVERTER.convert(value);
    }

    /**
     * Sets the value into system properties.
     * @param value to set
     */
    public void setInt(int value)
    {
        System.setProperty(key, Integer.toString(value));
    }

    /**
     * Gets the value of a system property as a long.
     * @return system property long value if it exists, defaultValue otherwise.
     */
    public long getLong()
    {
        String value = System.getProperty(key);

        return LONG_CONVERTER.convert(value == null ? defaultVal : value);
    }

    /**
     * Gets the value of a system property as a long.
     * @return system property long value if it exists, overrideDefaultValue otherwise.
     */
    public long getLong(int overrideDefaultValue)
    {
        String value = System.getProperty(key);
        if (value == null)
            return overrideDefaultValue;

        return LONG_CONVERTER.convert(value);
    }

    /**
     * Sets the value into system properties.
     * @param value to set
     */
    public void setLong(long value)
    {
        System.setProperty(key, Long.toString(value));
    }

    /**
     * Gets the value of a system property as a double.
     * @return system property double value if it exists, defaultValue otherwise.
     */
    public double getDouble()
    {
        String value = System.getProperty(key);

        return DOUBLE_CONVERTER.convert(value == null ? defaultVal : value);
    }

    /**
     * Gets the value of a system property as a double.
     * @return system property double value if it exists, overrideDefaultValue otherwise.
     */
    public double getDouble(double overrideDefaultValue)
    {
        String value = System.getProperty(key);
        if (value == null)
            return overrideDefaultValue;

        return DOUBLE_CONVERTER.convert(value);
    }

    /**
     * Sets the value into system properties.
     * @param value to set
     */
    public void setDouble(double value)
    {
        System.setProperty(key, Double.toString(value));
    }

    private interface PropertyConverter<T>
    {
        T convert(String value);
    }

    private static final PropertyConverter<String> STRING_CONVERTER = value -> value;

    private static final PropertyConverter<Boolean> BOOLEAN_CONVERTER = Boolean::parseBoolean;

    private static final PropertyConverter<Integer> INTEGER_CONVERTER = value ->
    {
        try
        {
            return Integer.decode(value);
        }
        catch (NumberFormatException e)
        {
            throw new ConfigurationException(String.format("Invalid value for system property: " +
                                                           "expected integer value but got '%s'", value));
        }
    };

    private static final PropertyConverter<Long> LONG_CONVERTER = value ->
    {
        try
        {
            return Long.decode(value);
        }
        catch (NumberFormatException e)
        {
            throw new ConfigurationException(String.format("Invalid value for system property: " +
                                                           "expected integer value but got '%s'", value));
        }
    };

    private static final PropertyConverter<Double> DOUBLE_CONVERTER = value ->
    {
        try
        {
            return Double.parseDouble(value);
        }
        catch (NumberFormatException e)
        {
            throw new ConfigurationException(String.format("Invalid value for system property: " +
                                                           "expected double value but got '%s'", value));
        }
    };

    /**
     * @return whether a system property is present or not.
     */
    public boolean isPresent()
    {
        return System.getProperties().containsKey(key);
    }
}
