/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.cassandra.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * The AccessLevel is an enum that expresses the authorized access level granted to an API user:
 * 
 * NONE       No access permitted.
 * READONLY   Only read access is allowed.
 * READWRITE  Read and write access is allowed.
 * FULL       Read, write, and remove access is allowed.
 */
public enum AccessLevel implements TEnum {
  NONE(0),
  READONLY(16),
  READWRITE(32),
  FULL(64);

  private final int value;

  private AccessLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AccessLevel findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 16:
        return READONLY;
      case 32:
        return READWRITE;
      case 64:
        return FULL;
      default:
        return null;
    }
  }
}
