= Using map type
:description: Use a map when pairs of related elements must be stored as a key-value pair.

A map relates one item to another with a key-value pair.
For each key, only one value may exist, and duplicates cannot be stored.
Both the key and the value are designated with a data type.

Using the map type, you can store timestamp-related information in user profiles.
Each element of the map is internally stored as a single column that you can modify, replace, delete, and query.
Each element can have an individual time-to-live and expire when the TTL ends.

== Prerequisite

* xref:developing/cql/keyspace-check.adoc[Keyspace] must exist

In the following example, each team listed in the `map` called `teams` will have a `year` of integer type and a `team name` of text type.
The table is named `cyclist_teams`.
The map collection is specified with a map column name and the pair of data types enclosed in angle brackets.

[tabs]
====
CQL::
+
--
[source,language-cql]
----
include::cassandra:example$CQL/sai/cyclist_teams-table.cql[tag=mapColumn]
----
--

Result::
+
--
[source,results]
----
include::cassandra:example$RESULTS/sai/select_all_from_cyclist_teams.result[]
----
--
====
