== column_definition
:description: Sets the column name, defines the data type, and optionally sets a column to static or counter.

Enclosed in parentheses after the table name, use a comma-separated list to define multiple columns.
All tables must have at least one https://cassandra.apache.org/_/glossary.html#primary-key[primary key] column.
Each column is defined using the following syntax: `+column_name cql_type_definition [STATIC | PRIMARY KEY] [, ...]+`

*Restriction:*

* A table must have at least one `PRIMARY KEY`.
* When `PRIMARY KEY` is at the end of a column definition, that column is the only primary key for the table, and is defined as the https://cassandra.apache.org/_/glossary.html#[partition-key][partition key].
* A static column cannot be a primary key.
* Primary keys can include frozen collections.

*column_name* ::
Use a unique name for each column in a table.
To preserve case or use special characters, enclose the name in double-quotes.
cql_type_definition ::
Defines the type of data allowed in the column.
See xref:reference:data-types.adoc[CQL data type] or a xref:reference:user-defined-type.adoc[user-defined type].
*STATIC* ::
Optional, the column has a single value.
*PRIMARY KEY* ::
When the `PRIMARY KEY` is one column, append PRIMARY KEY to the end of the column definition.
This is only schema information required to create a table.
When there is one primary key, it is the partition key;
the data is divided and stored by the unique values in this column: ``column_name cql_type_definition PRIMARY KEY``.
+
Alternatively, you can declare the primary key consisting of only one column in the same way as you declare a compound primary key.
