/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.harry.stress.config;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.cassandra.harry.gen.Generator;
import org.apache.cassandra.harry.op.Kind;
import org.apache.cassandra.harry.stress.RotationStrategy;
import org.apache.cassandra.harry.stress.VisitGenerator;

import static org.apache.cassandra.utils.LocalizeString.toLowerCaseLocalized;

/**
 * CLI settings for Harry stress test, following the same pattern as cassandra-stress.
 *
 * <p><b>NOTE:</b> this file was almost entirely generated by an LLM as a time-saving
 * scaffold. Our usual preference is programmatic APIs over CLI tooling for Harry, so
 * it wasn't obvious that hand-writing a full cassandra-stress-style argument parser
 * was worth the investment. Treat the parsing, help text, and option wiring here as
 * best-effort generated code: read it carefully before relying on any specific flag,
 * and don't assume every documented option is implemented or behaves exactly as the
 * help string suggests. If a long-lived CLI becomes important, this is a good
 * candidate to rewrite by hand (or replace with a real arg-parsing library).
 *
 * Usage:
 *   harry-stress -mode stress
 *                -cluster contact_points=host1,host2,host3 [port=9042] [ssl]
 *                -schema [keyspace=ks] [replication=DC1:3,DC2:3] [config=path/to/schema.yaml]
 *                -rate threads=1000 fixed=20000/s
 *                -ratio read=50
 *                -rotation strategy=fixed target=2000 replace_with_new=5 replace_with_visited=5 min_partition_idx=0 max_partition_idx=1000000
 *
 *   harry-stress -mode generate-sstables
 *                -schema [keyspace=ks] [replication=DC1:3,DC2:3] [config=path/to/schema.yaml]
 *                -output directory=/path/to/output visits=1000000 [sstable_size_mb=256]
 *                -rotation strategy=fixed target=2000 replace_with_new=5 replace_with_visited=5 min_partition_idx=0 max_partition_idx=1000000
 *
 * Node is initialized, moving to UNREGISTERED state
 *  - Usage: harry-stress [options]
 *  - Usage: -mode stress|generate-sstables
 *  -   stress                 Run stress test against a live cluster (default)
 *  -   generate-sstables      Generate SSTables on disk
 *  - Usage: -cluster contact_points=host1,host2,... [port=9042] [ssl]
 *  -   contact_points=?       Comma-separated list of node hosts/IPs to connect to (required for stress mode)
 *  -   port=?                 Native protocol port (default: 9042)
 *  -   ssl                    Enable SSL
 *  - Usage: -schema [keyspace=?] [replication=DC1:3,DC2:3] [config=path/to/schema.yaml]
 *  -   keyspace=?             Keyspace name (default: auto-generated with timestamp)
 *  -   replication=?          Replication in DC:RF format, comma-separated (default: DC1:3,DC2:3)
 *  -   config=?               Path to YAML schema config file with table definition and column populations
 *  - Usage: -rate [threads=?] [fixed=?/s]
 *  -   threads=?              Number of concurrent workers (default: 1000)
 *  -   fixed=?/s              Target operations per second (default: 20000/s)
 *  - Usage: -ratio [read=?]
 *  -   read=?                 Percentage of reads/validations, 0-100 (default: 50)
 *  - Usage: -rotation [strategy=fixed|random] [target=?] [replace_with_new=?] [replace_with_visited=?] [min_partition_idx=?] [max_partition_idx=?] [initial_lts=?]
 *  -   strategy=?             Rotation strategy: 'fixed' or 'random' (default: fixed)
 *  -   target=?               Target number of active partitions (default: 2000)
 *  -   replace_with_new=?     Partitions replaced with new per rotation cycle, fixed only (default: 5)
 *  -   replace_with_visited=? Partitions replaced with visited per rotation cycle, fixed only (default: 5)
 *  -   min_partition_idx=?    Minimum partition index, inclusive (default: 0)
 *  -   max_partition_idx=?    Maximum partition index, exclusive (default: 9223372036854775807)
 *  -   initial_lts=?          Initial logical timestamp to resume from (default: 0)
 *  -   partition_switch_interval=?  Visits between partition switch checks (default: 500)
 *  - Usage: -output directory=? visits=? [sstable_size_mb=?] [compression]
 *  -   directory=?            Output directory for generated SSTables (required for generate-sstables)
 *  -   visits=?               Total number of visits to generate (required for generate-sstables)
 *  -   sstable_size_mb=?      Max SSTable size in MiB before flushing to a new one (default: 128)
 *  -   compression            Enable SSTable compression (default: disabled)
 *  -   local_node_id=?        Generate only partitions owned by this node (requires -cluster)
 */
public class HarryStressSettings
{
    public final Mode mode;
    public final ClusterSettings cluster;
    public final SchemaSettings schema;
    public final RateSettings rate;
    public final RatioSettings ratio;
    public final RotationSettings rotation;
    public final OpsSettings ops;
    public final OutputSettings output;
    public final StressSchemaConfig schemaConfig;

    public HarryStressSettings(Mode mode,
                               ClusterSettings cluster,
                               SchemaSettings schema,
                               RateSettings rate,
                               RatioSettings ratio,
                               RotationSettings rotation,
                               OpsSettings ops,
                               OutputSettings output)
    {
        this.mode = mode;
        this.cluster = cluster;
        this.schema = schema;
        this.rate = rate;
        this.ratio = ratio;
        this.rotation = rotation;
        this.ops = ops;
        this.output = output;

        if (schema.configPath != null)
        {
            try
            {
                this.schemaConfig = StressSchemaConfig.load(Paths.get(schema.configPath));
            }
            catch (IOException e)
            {
                throw new RuntimeException("Failed to load schema config from " + schema.configPath, e);
            }
        }
        else
        {
            this.schemaConfig = null;
        }
    }

    public RotationStrategy buildRotationStrategy()
    {
        return rotation.buildRotationStrategy();
    }

    public Generator<VisitGenerator.VisitType> buildVisitTypeGen()
    {
        final int readPercent = ratio.readPercent;
        return rng -> rng.nextInt(100) < readPercent ? VisitGenerator.VisitType.VALIDATE : VisitGenerator.VisitType.MUTATE;
    }

    public VisitGenerator.OpKindGenFactory buildOpKindGenFactory()
    {
        return ops.buildOpKindGenFactory();
    }

    public void printSettings(PrintStream out)
    {
        out.println("******************** Harry Stress Settings ********************");
        out.println("Mode: " + mode);
        if (cluster != null)
        {
            out.println("Cluster:");
            cluster.printSettings(out);
        }
        out.println("Schema:");
        schema.printSettings(out);
        if (mode == Mode.STRESS)
        {
            out.println("Rate:");
            rate.printSettings(out);
            out.println("Ratio:");
            ratio.printSettings(out);
            out.println("Ops:");
            ops.printSettings(out);
        }
        if (output != null)
        {
            out.println("Output:");
            output.printSettings(out);
        }
        out.println("Rotation:");
        rotation.printSettings(out);
        out.println();
    }

    // ========================== Mode ==========================

    public enum Mode
    {
        STRESS,
        GENERATE_LEVELS,
        GENERATE_LEVELLED_SSTABLES;

        static Mode parse(String value)
        {
            switch (toLowerCaseLocalized(value))
            {
                case "stress": return STRESS;
                case "generate-levels": return GENERATE_LEVELS;
                case "generate-levelled-sstables": return GENERATE_LEVELLED_SSTABLES;
                default:
                    throw new IllegalArgumentException("Unknown mode: " + value);
            }
        }

        @Override
        public String toString()
        {
            switch (this)
            {
                case STRESS: return "stress";
                case GENERATE_LEVELS: return "generate-levels";
                case GENERATE_LEVELLED_SSTABLES: return "generate-levelled-sstables";
                default: throw new AssertionError();
            }
        }

        static Mode get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-mode");
            if (params == null || params.length == 0)
                return STRESS;
            if (params.length != 1)
                throw new IllegalArgumentException("-mode expects exactly one value: stress, generate-sstables, or generate-levels");
            return parse(params[0]);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -mode stress|generate-sstables|generate-levels");
            System.out.println();
            System.out.println("  stress                 Run stress test against a live cluster (default)");
            System.out.println("  generate-sstables      Generate SSTables on disk");
            System.out.println("  generate-levels        Generate token index level files");
        }
    }

    // ========================== Cluster Settings ==========================

    public static class ClusterSettings
    {
        public final String[] contactPoints;
        public final int port;
        public final boolean ssl;
        public final String dc;
        public final String username;
        public final String password;
        public final String consistencyLevel;
        public final String selectConsistencyLevel;
        public final int selectConsistencyLevelChance;
        public final String writeConsistencyLevel;
        public final int writeConsistencyLevelChance;
        public final String metricsOut;
        public final int reportIntervalSeconds;

        public ClusterSettings(ClusterOptions options)
        {
            this.contactPoints = options.contactPoints.value().split("\\s*,\\s*");
            this.port = Integer.parseInt(options.port.value());
            this.ssl = options.ssl.setByUser();
            this.dc = options.dc.setByUser() ? options.dc.value() : null;
            this.username = options.username.setByUser() ? options.username.value() : null;
            this.password = options.password.setByUser() ? options.password.value() : null;
            this.consistencyLevel = options.consistencyLevel.value();
            this.selectConsistencyLevel = options.selectConsistencyLevel.setByUser() ? options.selectConsistencyLevel.value() : null;
            this.selectConsistencyLevelChance = Integer.parseInt(options.selectConsistencyLevelChance.value());
            this.writeConsistencyLevel = options.writeConsistencyLevel.setByUser() ? options.writeConsistencyLevel.value() : null;
            this.writeConsistencyLevelChance = Integer.parseInt(options.writeConsistencyLevelChance.value());
            this.metricsOut = options.metricsOut.value();
            this.reportIntervalSeconds = Integer.parseInt(options.reportIntervalSeconds.value());
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Contact points: %s", String.join(", ", contactPoints)));
            out.println(String.format("  Port: %d", port));
            out.println(String.format("  SSL: %b", ssl));
            out.println(String.format("  DC: %s", dc != null ? dc : "<not set>"));
            out.println(String.format("  Username: %s", username != null ? username : "<not set>"));
            out.println(String.format("  Consistency Level: %s", consistencyLevel));
            if (selectConsistencyLevel != null)
                out.println(String.format("  Select Consistency Level: %s (%d%%)", selectConsistencyLevel, selectConsistencyLevelChance));
            if (writeConsistencyLevel != null)
                out.println(String.format("  Write Consistency Level: %s (%d%%)", writeConsistencyLevel, writeConsistencyLevelChance));
            if (metricsOut != null)
                out.println(String.format("  Metrics Out: %s", metricsOut));
        }

        static ClusterSettings get(Map<String, String[]> clArgs, boolean required)
        {
            String[] params = clArgs.remove("-cluster");
            if (params == null)
            {
                if (required)
                {
                    printHelp();
                    throw new IllegalArgumentException("-cluster is required in stress mode. Use -help for usage information.");
                }
                return null;
            }

            ClusterOptions options = new ClusterOptions();
            for (String param : params)
            {
                if (!options.accept(param))
                    throw new IllegalArgumentException("Invalid -cluster parameter: " + param);
            }
            if (!options.isValid())
                throw new IllegalArgumentException("Missing required -cluster parameters (contact_points=)");
            return new ClusterSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -cluster contact_points=host1,host2,... [port=9042] [ssl] [dc=?] [username=?] [password=?] [consistency_level=?]");
            System.out.println();
            System.out.println("  contact_points=?       Comma-separated list of node hosts/IPs to connect to (required for stress mode)");
            System.out.println("  port=?                 Native protocol port (default: 9042)");
            System.out.println("  ssl                    Enable SSL");
            System.out.println("  dc=?                   Data center name (optional)");
            System.out.println("  username=?             Cassandra username for authentication");
            System.out.println("  password=?             Cassandra password for authentication");
            System.out.println("  consistency_level=?    Consistency level (default: QUORUM)");
            System.out.println("  select_consistency_level=?  Consistency level for SELECTs (default: same as consistency_level)");
            System.out.println("  select_consistency_level_chance=?  Probability 0-100 of using select CL instead of default (default: 100)");
            System.out.println("  write_consistency_level=?   Consistency level for writes (default: same as consistency_level)");
            System.out.println("  write_consistency_level_chance=?   Probability 0-100 of using write CL instead of default (default: 100)");
        }
    }

    static class ClusterOptions
    {
        final SimpleOption contactPoints = new SimpleOption("contact_points=", ".*", null, true);
        final SimpleOption port = new SimpleOption("port=", "[0-9]+", "9042", false);
        final SimpleOption ssl = new SimpleOption("ssl", "", null, false);
        final SimpleOption dc = new SimpleOption("dc=", ".*", null, false);
        final SimpleOption username = new SimpleOption("username=", ".*", null, false);
        final SimpleOption password = new SimpleOption("password=", ".*", null, false);
        final SimpleOption consistencyLevel = new SimpleOption("consistency_level=", ".*", "QUORUM", false);
        final SimpleOption selectConsistencyLevel = new SimpleOption("select_consistency_level=", ".*", null, false);
        final SimpleOption selectConsistencyLevelChance = new SimpleOption("select_consistency_level_chance=", "[0-9]+", "100", false);
        final SimpleOption writeConsistencyLevel = new SimpleOption("write_consistency_level=", ".*", null, false);
        final SimpleOption writeConsistencyLevelChance = new SimpleOption("write_consistency_level_chance=", "[0-9]+", "100", false);
        final SimpleOption metricsOut = new SimpleOption("metrics_out=", ".*", null, false);
        final SimpleOption reportIntervalSeconds = new SimpleOption("report_interval=", "[0-9]+", "30", false);

        private final List<SimpleOption> all = Arrays.asList(contactPoints, port, ssl, dc, username, password, consistencyLevel, selectConsistencyLevel, selectConsistencyLevelChance, writeConsistencyLevel, writeConsistencyLevelChance, metricsOut);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Schema Settings ==========================

    public static class SchemaSettings
    {
        public final String keyspace;
        public final Map<String, String> replication;
        public final String configPath;

        public SchemaSettings(SchemaOptions options)
        {
            this.keyspace = options.keyspace.setByUser() ? options.keyspace.value() : null;
            this.replication = parseReplication(options.replication.value());
            this.configPath = options.config.setByUser() ? options.config.value() : null;
        }

        private static Map<String, String> parseReplication(String spec)
        {
            Map<String, String> result = new LinkedHashMap<>();
            if (spec == null || spec.isEmpty())
                return result;
            for (String pair : spec.split(","))
            {
                String[] kv = pair.split(":");
                if (kv.length != 2)
                    throw new IllegalArgumentException("Invalid replication spec, expected DC:RF pairs separated by commas, got: " + spec);
                result.put(kv[0].trim(), kv[1].trim());
            }
            return result;
        }

        public String buildKeyspaceDDL(String keyspaceName)
        {
            StringBuilder sb = new StringBuilder();
            sb.append("CREATE KEYSPACE IF NOT EXISTS ").append(keyspaceName)
              .append(" WITH replication = { 'class' : 'org.apache.cassandra.locator.NetworkTopologyStrategy'");
            for (Map.Entry<String, String> entry : replication.entrySet())
                sb.append(", '").append(entry.getKey()).append("': '").append(entry.getValue()).append("'");
            sb.append(" };");
            return sb.toString();
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Keyspace: %s", keyspace != null ? keyspace : "auto-generated"));
            out.println(String.format("  Replication: %s", replication));
            if (configPath != null)
                out.println(String.format("  Config: %s", configPath));
        }

        static SchemaSettings get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-schema");
            SchemaOptions options = new SchemaOptions();
            if (params != null)
            {
                for (String param : params)
                {
                    if (!options.accept(param))
                        throw new IllegalArgumentException("Invalid -schema parameter: " + param);
                }
            }
            return new SchemaSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -schema [keyspace=?] [replication=DC1:3,DC2:3] [config=path/to/schema.yaml]");
            System.out.println();
            System.out.println("  keyspace=?             Keyspace name (default: auto-generated with timestamp)");
            System.out.println("  replication=?          Replication in DC:RF format, comma-separated (default: DC1:3,DC2:3)");
            System.out.println("  config=?               Path to YAML schema config file with table definition and column populations");
        }
    }

    static class SchemaOptions
    {
        final SimpleOption keyspace = new SimpleOption("keyspace=", ".*", null, false);
        final SimpleOption replication = new SimpleOption("replication=", ".*", "DC1:3,DC2:3", false);
        final SimpleOption config = new SimpleOption("config=", ".*", null, false);

        private final List<SimpleOption> all = Arrays.asList(keyspace, replication, config);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Rate Settings ==========================

    public static class RateSettings
    {
        public final int concurrency;
        public final int ratePerSecond;

        public RateSettings(RateOptions options)
        {
            this.concurrency = Integer.parseInt(options.threads.value());
            String rateStr = options.fixed.value();
            this.ratePerSecond = Integer.parseInt(rateStr.endsWith("/s") ? rateStr.substring(0, rateStr.length() - 2) : rateStr);
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Threads: %d", concurrency));
            out.println(String.format("  Rate/s: %d", ratePerSecond));
        }

        static RateSettings get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-rate");
            RateOptions options = new RateOptions();
            if (params != null)
            {
                for (String param : params)
                {
                    if (!options.accept(param))
                        throw new IllegalArgumentException("Invalid -rate parameter: " + param);
                }
            }
            return new RateSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -rate [threads=?] [fixed=?/s]");
            System.out.println();
            System.out.println("  threads=?              Number of concurrent workers (default: 1000)");
            System.out.println("  fixed=?/s              Target operations per second (default: 20000/s)");
        }
    }

    static class RateOptions
    {
        final SimpleOption threads = new SimpleOption("threads=", "[0-9]+", "1000", false);
        final SimpleOption fixed = new SimpleOption("fixed=", "[0-9]+(/s)?", "20000/s", false);

        private final List<SimpleOption> all = Arrays.asList(threads, fixed);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Ratio Settings ==========================

    public static class RatioSettings
    {
        public final int readPercent;

        public RatioSettings(RatioOptions options)
        {
            this.readPercent = Integer.parseInt(options.read.value());
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Read: %d%%", readPercent));
            out.println(String.format("  Write: %d%%", 100 - readPercent));
        }

        static RatioSettings get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-ratio");
            RatioOptions options = new RatioOptions();
            if (params != null)
            {
                for (String param : params)
                {
                    if (!options.accept(param))
                        throw new IllegalArgumentException("Invalid -ratio parameter: " + param);
                }
            }
            return new RatioSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -ratio [read=?]");
            System.out.println();
            System.out.println("  read=?                 Percentage of reads/validations, 0-100 (default: 50)");
        }
    }

    static class RatioOptions
    {
        final SimpleOption read = new SimpleOption("read=", "[0-9]+", "50", false);

        private final List<SimpleOption> all = Arrays.asList(read);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Ops Settings ==========================

    public static class OpsSettings
    {
        public final int insertWeight;
        public final int updateWeight;
        public final int selectPartitionWeight;
        public final int selectRowWeight;
        public final int selectRangeWeight;

        public OpsSettings(OpsOptions options)
        {
            this.insertWeight = Integer.parseInt(options.insert.value());
            this.updateWeight = Integer.parseInt(options.update.value());
            this.selectPartitionWeight = Integer.parseInt(options.selectPartition.value());
            this.selectRowWeight = Integer.parseInt(options.selectRow.value());
            this.selectRangeWeight = Integer.parseInt(options.selectRange.value());
        }

        public VisitGenerator.OpKindGenFactory buildOpKindGenFactory()
        {
            VisitGenerator.WeightedOpKindGenFactory.Builder builder = VisitGenerator.WeightedOpKindGenFactory.builder();
            builder.mutate(Kind.INSERT, insertWeight);
            builder.mutate(Kind.UPDATE, updateWeight);
            builder.validate(Kind.SELECT_PARTITION, selectPartitionWeight);
            builder.validate(Kind.SELECT_ROW, selectRowWeight);
            builder.validate(Kind.SELECT_RANGE, selectRangeWeight);
            return builder.build();
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Write: insert=%d, update=%d",
                                      insertWeight, updateWeight));
            out.println(String.format("  Read:  select_partition=%d, select_row=%d, select_range=%d",
                                      selectPartitionWeight, selectRowWeight, selectRangeWeight));
        }

        static OpsSettings get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-ops");
            OpsOptions options = new OpsOptions();
            if (params != null)
            {
                for (String param : params)
                {
                    if (!options.accept(param))
                        throw new IllegalArgumentException("Invalid -ops parameter: " + param);
                }
            }
            return new OpsSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -ops [insert=?] [update=?] [select_partition=?] [select_row=?] [select_range=?]");
            System.out.println();
            System.out.println("  insert=?               Weight for INSERT (default: 1)");
            System.out.println("  update=?               Weight for UPDATE (default: 1)");
            System.out.println("  select_partition=?     Weight for SELECT_PARTITION (default: 1)");
            System.out.println("  select_row=?           Weight for SELECT_ROW (default: 1)");
            System.out.println("  select_range=?         Weight for SELECT_RANGE (default: 1)");
        }
    }

    static class OpsOptions
    {
        final SimpleOption insert = new SimpleOption("insert=", "[0-9]+", "1", false);
        final SimpleOption update = new SimpleOption("update=", "[0-9]+", "1", false);
        final SimpleOption selectPartition = new SimpleOption("select_partition=", "[0-9]+", "1", false);
        final SimpleOption selectRow = new SimpleOption("select_row=", "[0-9]+", "1", false);
        final SimpleOption selectRange = new SimpleOption("select_range=", "[0-9]+", "1", false);

        private final List<SimpleOption> all = Arrays.asList(insert, update, selectPartition, selectRow, selectRange);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Rotation Settings ==========================

    public static class RotationSettings
    {
        public final String strategy; // "fixed" or "random"
        public final int targetSize;
        // fixed-only
        public final int replaceWithNew;
        public final int replaceWithVisited;
        public final int partitionSwitchInterval;
        public final long minPartitionIdx;
        public final long maxPartitionIdx;
        public final long initialLts;
        public final File ltsProgressFile;

        public RotationSettings(RotationOptions options)
        {
            this.strategy = options.strategy.value();
            this.targetSize = Integer.parseInt(options.target.value());
            this.replaceWithNew = Integer.parseInt(options.replaceWithNew.value());
            this.replaceWithVisited = Integer.parseInt(options.replaceWithVisited.value());
            this.partitionSwitchInterval = Integer.parseInt(options.partitionSwitchInterval.value());
            this.minPartitionIdx = Long.parseLong(options.minPartitionIdx.value());
            this.maxPartitionIdx = Long.parseLong(options.maxPartitionIdx.value());
            this.initialLts = Long.parseLong(options.initialLts.value());
            this.ltsProgressFile = options.ltsProgressFile.setByUser() ? new File(options.ltsProgressFile.value()) : null;
        }

        public RotationStrategy buildRotationStrategy()
        {
            switch (strategy)
            {
                case "fixed":
                    return new RotationStrategy.FixedRotationStrategy(targetSize, replaceWithNew, replaceWithVisited, partitionSwitchInterval);
                case "random":
                    return new RotationStrategy.RandomRotationStrategy(targetSize, partitionSwitchInterval);
                default:
                    throw new IllegalArgumentException("Unknown rotation strategy: " + strategy + ". Expected 'fixed' or 'random'.");
            }
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Strategy: %s", strategy));
            out.println(String.format("  Target Size: %d", targetSize));
            if ("fixed".equals(strategy))
            {
                out.println(String.format("  Replace With New: %d", replaceWithNew));
                out.println(String.format("  Replace With Visited: %d", replaceWithVisited));
            }
            out.println(String.format("  Min Partition Idx: %d", minPartitionIdx));
            out.println(String.format("  Max Partition Idx: %d", maxPartitionIdx));
            out.println(String.format("  Initial LTS: %d", initialLts));
            out.println(String.format("  Partition Switch Interval: %d", partitionSwitchInterval));
        }

        static RotationSettings get(Map<String, String[]> clArgs)
        {
            String[] params = clArgs.remove("-rotation");
            RotationOptions options = new RotationOptions();
            if (params != null)
            {
                for (String param : params)
                {
                    if (!options.accept(param))
                        throw new IllegalArgumentException("Invalid -rotation parameter: " + param);
                }
            }
            return new RotationSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -rotation [strategy=fixed|random] [target=?] [replace_with_new=?] [replace_with_visited=?] [min_partition_idx=?] [max_partition_idx=?] [initial_lts=?]");
            System.out.println();
            System.out.println("  strategy=?             Rotation strategy: 'fixed' or 'random' (default: fixed)");
            System.out.println("  target=?               Target number of active partitions (default: 2000)");
            System.out.println("  replace_with_new=?     Partitions replaced with new per rotation cycle, fixed only (default: 5)");
            System.out.println("  replace_with_visited=? Partitions replaced with visited per rotation cycle, fixed only (default: 5)");
            System.out.println("  min_partition_idx=?    Minimum partition index, inclusive (default: 0)");
            System.out.println("  max_partition_idx=?    Maximum partition index, exclusive (default: " + Long.MAX_VALUE + ")");
            System.out.println("  initial_lts=?          Initial logical timestamp to resume from (default: 0)");
            System.out.println("  partition_switch_interval=?  Visits between partition switch checks (default: 500)");
        }
    }

    static class RotationOptions
    {
        final SimpleOption strategy = new SimpleOption("strategy=", "(fixed|random)", "fixed", false);
        final SimpleOption target = new SimpleOption("target=", "[0-9]+", "2000", false);
        final SimpleOption replaceWithNew = new SimpleOption("replace_with_new=", "[0-9]+", "5", false);
        final SimpleOption replaceWithVisited = new SimpleOption("replace_with_visited=", "[0-9]+", "5", false);
        final SimpleOption minPartitionIdx = new SimpleOption("min_partition_idx=", "[0-9]+", "0", false);
        final SimpleOption maxPartitionIdx = new SimpleOption("max_partition_idx=", "[0-9]+", Long.toString(Long.MAX_VALUE), false);
        final SimpleOption initialLts = new SimpleOption("initial_lts=", "[0-9]+", "0", false);
        final SimpleOption ltsProgressFile = new SimpleOption("lts_progress_file=", ".*", null, false);
        final SimpleOption partitionSwitchInterval = new SimpleOption("partition_switch_interval=", "[0-9]+", "500", false);

        private final List<SimpleOption> all = Arrays.asList(strategy, target, replaceWithNew, replaceWithVisited, minPartitionIdx, maxPartitionIdx, initialLts, ltsProgressFile, partitionSwitchInterval);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Output Settings (generate-sstables mode) ==========================

    public static class OutputSettings
    {
        public final String directory;
        public final long visits;
        public final int sstableSizeMiB;
        public final boolean noCompression;
        public final String localNodeId; // null if not specified
        public final Long minToken, maxToken;
        public final String tokenIndex; // path to token index data file (without .idx extension)
        public final String levels; // comma-separated level weights, e.g. "1,10,100,500,1000,2000"
        public final long maxPartitions; // max partitions to write (default: unlimited)

        public OutputSettings(OutputOptions options)
        {
            this.directory = options.directory.value();
            this.visits = Long.parseLong(options.visits.value());
            this.sstableSizeMiB = Integer.parseInt(options.sstableSizeMb.value());
            this.noCompression = !options.compression.setByUser();
            this.localNodeId = options.localNodeId.setByUser() ? options.localNodeId.value() : null;
            this.minToken = options.minToken.setByUser() ? Long.parseLong(options.minToken.value()) : null;
            this.maxToken = options.maxToken.setByUser() ? Long.parseLong(options.maxToken.value()) : null;
            this.tokenIndex = options.tokenIndex.setByUser() ? options.tokenIndex.value() : null;
            this.levels = options.levels.setByUser() ? options.levels.value() : null;
            this.maxPartitions = options.maxPartitions.setByUser() ? Long.parseLong(options.maxPartitions.value()) : Long.MAX_VALUE;
        }

        public void printSettings(PrintStream out)
        {
            out.println(String.format("  Directory: %s", directory));
            out.println(String.format("  Visits: %d", visits));
            out.println(String.format("  SSTable Size: %d MiB", sstableSizeMiB));
            out.println(String.format("  Compression: %s", noCompression ? "disabled" : "enabled (LZ4)"));
            if (localNodeId != null)
                out.println(String.format("  Local Node ID: %s", localNodeId));
            if (maxPartitions != Long.MAX_VALUE)
                out.println(String.format("  Max Partitions: %d", maxPartitions));
        }

        static OutputSettings get(Map<String, String[]> clArgs, boolean required)
        {
            String[] params = clArgs.remove("-output");
            if (params == null)
            {
                if (required)
                {
                    printHelp();
                    throw new IllegalArgumentException("-output is required in generate-sstables mode (directory=, visits=). Use -help for usage information.");
                }
                return null;
            }

            OutputOptions options = new OutputOptions();
            for (String param : params)
            {
                if (!options.accept(param))
                    throw new IllegalArgumentException("Invalid -output parameter: " + param);
            }
            if (!options.isValid())
                throw new IllegalArgumentException("Missing required -output parameters (directory=, visits=)");
            return new OutputSettings(options);
        }

        static void printHelp()
        {
            System.out.println();
            System.out.println("Usage: -output directory=? visits=? [sstable_size_mb=?] [compression]");
            System.out.println();
            System.out.println("  directory=?            Output directory for generated SSTables (required for generate-sstables)");
            System.out.println("  visits=?               Total number of visits to generate (required for generate-sstables)");
            System.out.println("  sstable_size_mb=?      Max SSTable size in MiB before flushing to a new one (default: 128)");
            System.out.println("  compression            Enable SSTable compression (default: disabled)");
            System.out.println("  local_node_id=?        Generate only partitions owned by this node (requires -cluster)");
            System.out.println("  max_partitions=?       Max number of partitions to write (default: unlimited)");
        }
    }

    static class OutputOptions
    {
        final SimpleOption directory = new SimpleOption("directory=", ".*", null, true);
        final SimpleOption visits = new SimpleOption("visits=", "[0-9]+", null, true);
        final SimpleOption sstableSizeMb = new SimpleOption("sstable_size_mb=", "[0-9]+", "128", false);
        final SimpleOption compression = new SimpleOption("compression", "", null, false);
        final SimpleOption localNodeId = new SimpleOption("local_node_id=", ".*", null, false);
        final SimpleOption minToken = new SimpleOption("min_token=", "-?[0-9]+", null, false);
        final SimpleOption maxToken = new SimpleOption("max_token=", "-?[0-9]+", null, false);
        final SimpleOption tokenIndex = new SimpleOption("token_index=", ".*", null, false);
        final SimpleOption levels = new SimpleOption("levels=", ".*", null, false);
        final SimpleOption maxPartitions = new SimpleOption("max_partitions=", "[0-9]+", null, false);

        private final List<SimpleOption> all = Arrays.asList(directory, visits, sstableSizeMb, compression, localNodeId, minToken, maxToken, tokenIndex, levels, maxPartitions);

        boolean accept(String param)
        {
            for (SimpleOption opt : all)
                if (opt.accept(param))
                    return true;
            return false;
        }

        boolean isValid()
        {
            for (SimpleOption opt : all)
                if (!opt.isValid())
                    return false;
            return true;
        }
    }

    // ========================== Simple Option (lightweight, self-contained) ==========================

    /**
     * A lightweight option parser, modeled after cassandra-stress's OptionSimple but self-contained
     * so harry-stress doesn't depend on the stress tool module.
     */
    static class SimpleOption
    {
        final String prefix;
        final String pattern;
        final String defaultValue;
        final boolean required;
        private String value;

        SimpleOption(String prefix, String pattern, String defaultValue, boolean required)
        {
            this.prefix = prefix;
            this.pattern = pattern;
            this.defaultValue = defaultValue;
            this.required = required;
        }

        boolean accept(String param)
        {
            String lower = toLowerCaseLocalized(param);
            String lowerPrefix = toLowerCaseLocalized(prefix);

            // Flag-style option (no value, e.g. "ssl")
            if (pattern.isEmpty())
            {
                if (lower.equals(lowerPrefix))
                {
                    value = "";
                    return true;
                }
                return false;
            }

            // Key=value style
            if (lower.startsWith(lowerPrefix))
            {
                String v = param.substring(prefix.length());
                if (!v.matches(pattern))
                    throw new IllegalArgumentException("Invalid value '" + v + "' for " + prefix + "; must match " + pattern);
                value = v;
                return true;
            }
            return false;
        }

        boolean setByUser()
        {
            return value != null;
        }

        String value()
        {
            return value != null ? value : defaultValue;
        }

        boolean isValid()
        {
            return !required || value != null;
        }
    }

    // ========================== Parsing ==========================

    public static HarryStressSettings parse(String[] args)
    {
        args = repairParams(args);
        Map<String, String[]> clArgs = parseMap(args);

        if (clArgs.containsKey("-help") || clArgs.containsKey("--help") || clArgs.containsKey("-h"))
        {
            printHelp();
            System.exit(0);
        }

        Mode mode = Mode.get(clArgs);

        ClusterSettings cluster = ClusterSettings.get(clArgs, mode == Mode.STRESS);
        SchemaSettings schema = SchemaSettings.get(clArgs);
        RateSettings rate = RateSettings.get(clArgs);
        RatioSettings ratio = RatioSettings.get(clArgs);
        OpsSettings ops = OpsSettings.get(clArgs);
        RotationSettings rotation = RotationSettings.get(clArgs);
        OutputSettings output = OutputSettings.get(clArgs, mode == Mode.GENERATE_LEVELS || mode == Mode.GENERATE_LEVELLED_SSTABLES);

        if (!clArgs.isEmpty())
        {
            printHelp();
            System.out.println("Error processing command line arguments. The following were ignored:");
            for (Map.Entry<String, String[]> e : clArgs.entrySet())
            {
                System.out.print(e.getKey());
                for (String v : e.getValue())
                {
                    System.out.print(" ");
                    System.out.print(v);
                }
                System.out.println();
            }
            System.exit(1);
        }

        return new HarryStressSettings(mode, cluster, schema, rate, ratio, rotation, ops, output);
    }

    private static String[] repairParams(String[] args)
    {
        if (args.length == 0)
            return args;
        StringBuilder sb = new StringBuilder();
        boolean first = true;
        for (String arg : args)
        {
            if (!first)
                sb.append(" ");
            sb.append(arg);
            first = false;
        }
        return sb.toString()
                 .replaceAll("\\s+([,=()])", "$1")
                 .replaceAll("([,=(])\\s+", "$1")
                 .split(" +");
    }

    private static Map<String, String[]> parseMap(String[] args)
    {
        if (args.length == 0)
        {
            printHelp();
            System.exit(1);
        }
        final LinkedHashMap<String, String[]> r = new LinkedHashMap<>();
        String key = null;
        List<String> params = new ArrayList<>();
        for (int i = 0; i < args.length; i++)
        {
            if (args[i].startsWith("-"))
            {
                if (key != null)
                    putParam(key, params.toArray(new String[0]), r);
                key = toLowerCaseLocalized(args[i]);
                params.clear();
            }
            else
            {
                params.add(args[i]);
            }
        }
        if (key != null)
            putParam(key, params.toArray(new String[0]), r);
        return r;
    }

    private static void putParam(String key, String[] args, Map<String, String[]> clArgs)
    {
        String[] prev = clArgs.put(key, args);
        if (prev != null)
            throw new IllegalArgumentException(key + " is defined multiple times. Each option can be specified at most once.");
    }

    public static void printHelp()
    {
        System.out.println();
        System.out.println("Usage: harry-stress [options]");
        System.out.println();
        Mode.printHelp();
        ClusterSettings.printHelp();
        SchemaSettings.printHelp();
        RateSettings.printHelp();
        RatioSettings.printHelp();
        OpsSettings.printHelp();
        RotationSettings.printHelp();
        OutputSettings.printHelp();
    }
}
