# docker-compose.yml for building the Cassandra documentation.

version: '2.0'

services:
  build-docs:
    build: .
    volumes:
      - ..:/usr/src/code
    environment:
      - SKIP_NODETOOL # set this to skip nodetool build, saves a lot of time when debugging html
