site:
  title: Apache Cassandra Documentation
  url: file:///Users/lorina.poland/CLONES/cassandra/build/html/Cassandra/4.0
  # UNCOMMENT WHEN READY
  #keys:
  # google_analytics: 'UA-11583863-1'
  #start_page: ROOT::index.adoc

content:
  sources: 
  #- url: /antora/cassandra
  - url: https://github.com/polandll/cassandra.git
    branches: 
    - 'doc_redo_asciidoc'
    #- 'doc_redo_asciidoc3.11'
    start_path: doc/source
  - url: https://github.com/polandll/cassandra-website.git
    branches:
    - test_new_doc_builder
    start_path: source

ui:
  # Need to replace this with a direct github url rather than a local path
  bundle:
    #url: /antora/cassandra/doc/ui-bundle.zip
    #url: /Users/lorina.poland/CLONES/antora-ui-datastax/build/ui-bundle.zip
    #url: https://github.com/ianjevans/antora-ui-datastax/build/ui-bundle.zip
    url: https://github.com/ianjevans/antora-ui-datastax/releases/download/v0.1oss/ui-bundle.zip
    snapshot: true
  #supplemental_files: ./supplemental_ui

output:
    clean: true
    dir: ./build/html

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    experimental: ''
    source-language: asciidoc
    current-version: 4.0
    latest-version: 4.0
    previous-version: 3.11
    40_version: '4.0'
    3x_version: '3.11'
    30_version: '3.0'
    22_version: '2.2'
    21_version: '2.1'
    example-caption: ~
    hide-uri-scheme: ''
    linkattrs: ''
    table-caption: ~
    tabs: tabs
    page-pagination: true
    url-project: https://asciidoctor.org
    url-org: https://github.com/asciidoctor
    url-exten-lab: https://github.com/asciidoctor/asciidoctor-extensions-lab
    url-rubygem: https://rubygems.org/gems/asciidoctor
    url-tilt: https://github.com/rtomayko/tilt
    url-foundation: https://foundation.zurb.com
    url-jruby: https://jruby.org
    #url-asciimath: https://docs.mathjax.org/en/latest/asciimath.html
    #url-latexmath: https://docs.mathjax.org/en/latest/tex.html
    #url-mathjax: https://www.mathjax.org
    #url-mathjax-docs: https://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference
    #url-coderay: http://coderay.rubychan.de/
    #url-coderay-gem: https://rubygems.org/gems/coderay
    url-highlightjs: https://highlightjs.org/
    url-highlightjs-lang: https://highlightjs.org/download/
    url-prettify: https://code.google.com/p/google-code-prettify
    url-pygments: http://pygments.org
    url-pygments-lang: http://pygments.org/languages/
    url-pygments-gem: https://rubygems.org/gems/pygments.rb
    url-python: https://www.python.org
    #url-rouge: http://rouge.jneen.net
  extensions:
  - ./lib/tabs-block.js
