#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

schema:
  version: 1

sonarw_output_dir: 'sonarqube' # Non-overridable

connection: # Non-overridable
  sonarqube:
    production:
      udg_path: 'udg://sonarqube-udg'
      zones:
        - 'dca11'
        - 'dca4'
    staging:
      udg_path: 'udg://sonarqube-udg-staging'
      zones:
        - 'dca11'
        - 'dca4'

sonarqube:
  sources:  # Overridable (extendable list)
    - "**/src/java/org/apache/cassandra/**/*.java"
  source_exclusions: # Overridable (extendable list)
    - "**/test/**/*"
    - "*.py"
    - "**/tools/**"
    - "**/hadoop/**"
  static_analysis: # Overridable (addition disallowed)
    # Each language has 2 options:
    #   (a) UberNone  - Disables static analysis and reports only code coverage
    #   (b) UberAll   - Enables static analysis and is noisy since all the rules are enabled
    java: UberAll
    kotlin: UberNone
  unit_test_coverage:
    location: build/jacoco/report.xml     # Path to coverage file
    exclusions:
      file_path_patterns:                   # Overridable (extendable list)
        - "**/test/**/*"
        - "*.py"
        - "**/tools/**"
        - "**/hadoop/**"
      file_content_patterns:
