= Vector Search Quickstart

To enable your machine learning model, Vector Search uses data to be compared by similarity within a database, even if it is not explicitly defined by a connection. A vector is an array of floating point type that represents a specific object or entity.

The foundation of Vector Search lies within the embeddings, which are compact representations of text as vectors of floating-point numbers. These embeddings are generated by feeding the text through an API, which uses a neural network to transform the input into a fixed-length vector. Embeddings capture the semantic meaning of the text, providing a more nuanced understanding than traditional term-based approaches. The vector representation allows for input that is substantially similar to produce output vectors that are geometrically close; inputs that are not similar are geometrically further apart.

To enable Vector Search, a new `vector` data type is available in your {cassandra} database with Vector Search. 

== Prerequisites

There are no prerequisite tasks.

In general, to use Vector Search with Apache Cassandra, you'll follow these instructions:

The embeddings were randomly generated in this quickstart. 
Generally, you would run both your source documents/contents through an embeddings generator, as well as the query you were asking to match.
This example is simply to show the mechanics of how to use CQL to create vector search data objects.

include::../vector-search/_create-vector-keyspace-cycling.adoc[leveloffset=+1]

include::../vector-search/_use-vector-keyspace-cycling.adoc[leveloffset=+1]

include::../vector-search/_create-vector-table-cycling.adoc[leveloffset=+1]

include::../vector-search/_create-vector-index-cycling.adoc[leveloffset=+1]

include::../vector-search/_load-vector-data-cycling.adoc[leveloffset=+1]

include::../vector-search/_query-vector-data-cycling.adoc[leveloffset=+1]

With the code examples, you have a working example of our Vector Search. 
Load your own data and use the search function.