#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#set -o xtrace
set -o errexit
set -o pipefail
set -o nounset

bin="$(cd "$(dirname "$0")" > /dev/null; pwd)"
home="$(cd "$bin/../.." > /dev/null; pwd)" # this script lives in .build/sh

usage() {
  if [[ $# -gt 0 ]]; then
    echo "$*" 1>&2
  fi
  cat <<EOF
Usage: $(basename "$0") (options)*
Options:
--no-checkstyle     - runs with all checkstyle disabled
-h|--help           - this help page
EOF
  exit 1
}

no_checkstyle=false

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --no-checkstyle)
      no_checkstyle=true
      shift
      ;;
    -h|--help)
      usage
      shift
      ;;
    *)
      usage "Unknown argument $1"
      ;;
  esac
done

# Switch to the project root so all commands work properly
cd "$home"

opts=(
  -Dant.gen-doc.skip=true
  -Drat.skip=true
)

if [ $no_checkstyle ]; then
  ant -Dno-checkstyle=true "${opts[@]}" clean jar "$@" 2>&1 | "$bin"/ant-log-summary.py -
else
  ant "${opts[@]}" clean jar checkstyle checkstyle-test "$@" 2>&1 | "$bin"/ant-log-summary.py -
fi

