#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#set -o xtrace
set -o errexit
set -o pipefail
set -o nounset

bin="$(cd "$(dirname "$0")" > /dev/null; pwd)"
home="$(cd "$bin/../.." > /dev/null; pwd)" # this script lives in .build/sh

# Switch to the project root so all commands work properly
cd "$home"

usage() {
  if [[ $# -gt 0 ]]; then
    echo "$*" 1>&2
  fi
  cat <<EOF
Usage: $(basename "$0") [class name] (option)*

Options:
EOF
  exit 1
}

_main() {
  local class_name=""
  fresh_build=true
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --reuse)
        fresh_build=false
        shift
        ;;
      -h|--help)
        usage
        shift
        ;;
      *)
        if [[ -z "${class_name:-}" ]]; then
          class_name="$1"
          shift
        else
          usage "Unknown argument $1"
        fi
        ;;
    esac
  done

  if [[ -z "${class_name:-}" ]]; then
    usage "No class provided"
  fi

  path="$(echo "$class_name" | tr '.' '/' ).java"

  if $fresh_build; then
    if [[ ! "$path" =~ distributed/upgrade ]]; then
      ant realclean && ant && ant generate-idea-files
    fi
  fi

  counter=1
  echo ">>> Running attempt $counter"
  while "$bin"/ci-test "$class_name" --reuse; do
    counter=$(( counter + 1 ))
    echo ">>> Running attempt $counter"
  done;
  echo "Exited after $counter attempts"
}

_main "$@"
