alter_role_statement ::= ALTER ROLE [ IF EXISTS ] role_name ( WITH <option> ( AND <option> )* )?

<option> ::= PASSWORD = <string>
           | HASHED PASSWORD = <string>
           | GENERATED PASSWORD
           | LOGIN = <boolean>
           | SUPERUSER = <boolean>
           | OPTIONS = <map_literal>
           | ACCESS TO DATACENTERS <set_literal>
           | ACCESS TO ALL DATACENTERS
           | ACCESS FROM CIDRS <set_literal>
           | ACCESS FROM ALL CIDRS
