create_index_statement::= CREATE [ CUSTOM ] INDEX [ IF NOT EXISTS ] [ index_name ] 
	ON table_name '(' index_identifier ')' 
	[ USING string [ WITH OPTIONS = map_literal ] ] 
index_identifier::= column_name 
	| ( KEYS | VALUES | ENTRIES | FULL ) '(' column_name ')'
