delete_statement::= DELETE [ simple_selection ( ',' simple_selection ) ] 
	FROM table_name 
	[ USING update_parameter ( AND update_parameter# )* ] 
	WHERE where_clause 
	[ IF ( EXISTS | condition ( AND condition)*) ]
