== Query vector data with CQL

To query data using Vector Search, use a `SELECT` query:

[source,cql]
----
include::cassandra:example$CQL/vector-search/select-vsearch-cycling.cql[]
----

To obtain the distance calculation of the best scoring node closest to the query data as part of the results, use a `SELECT` query:

[source,cql]
----
include::cassandra:example$CQL/vector-search/select-vsearch-distance.cql[]
----

The supported functions for this type of query are:

* similarity_dot_product
* similarity_cosine
* similarity_euclidean

with the parameters of (<vector_column>, <embedding_value>).
Both parameters represent vectors.

[NOTE]
====
* The limit must be 1,000 or fewer.
* Vector Search utilizes Approximate Nearest Neighbor (ANN) that in most cases yields results almost as good as the exact match. The scaling is superior to Exact Nearest Neighbor (KNN).

* Least-similar searches are not supported.
* Vector Search works optimally on tables with no overwrites or deletions of the `item_vector` column. For an `item_vector` column with changes, expect slower search results.
====